### ISSUE TITLE
Error  while running "make"

### ISSUE THREAD

**Issue by ARao0123** [zoulasc/racoon2#1]
I'm running the following commands in racoon dir (outside iked,kinkd):

```
make distclean
CFLAGS=-D_GNU_SOURCE ./configure
make
```
I see the following error. Any idea what I'm doing wrong?

```
vmbuf.c: In function ‘vmemcmp’:
vmbuf.c:145:6: error: pointer targets in assignment differ in signedness [-Werror=pointer-sign]
   p1 = s1->v;
      ^
vmbuf.c:146:6: error: pointer targets in assignment differ in signedness [-Werror=pointer-sign]
   p2 = s2->v;
      ^
cc1: all warnings being treated as errors
```

**Comment by zoulasc** [comment]
What OS and compiler is that?

**Comment by zoulasc** [comment]
And the assignment lines have a cast....

**Comment by ARao0123** [comment]
This is on Ubuntu and compiler is gcc.

`gcc (Ubuntu 4.9.4-2ubuntu1~14.04.1) 4.9.4`

**Comment by zoulasc** [comment]
Ok, I think I fixed it, tested with on an odroidc1...
gcc version 7.3.0 (Ubuntu/Linaro 7.3.0-27ubuntu1~18.04)

**Comment by zoulasc** [comment]
Tested on linux
