### ISSUE TITLE
Autotools?

### ISSUE THREAD

**Issue by vanrein** [zoulasc/racoon2#7]
There is no more a `configure` script as indicated in `doc/INSTALL`; could you please give instructions of the right way of using `autotools`?  I looked for tagged versions, or packages with a `configure` included, and found none.  Is there perhaps a download site for recent stable versions that I missed?

**Comment by zoulasc** [comment]
configure is a generated file. Run 'autoreconf -f -i' on the top of the tree to regenerate it.

**Comment by vanrein** [comment]
Thanks.  I found it later, in the CI script, but now they are in the docs it has a better place :)
